In [1]:
import numpy as np
import random

# 1. Create a 3x3x3 array with random values 

In [18]:
np.random.rand(3,3,3)

array([[[0.60064005, 0.28193122, 0.1792278 ],
        [0.84921492, 0.15880237, 0.61936962],
        [0.6323258 , 0.59246668, 0.94159862]],

       [[0.61516849, 0.04033746, 0.51780051],
        [0.60920336, 0.65256418, 0.16778344],
        [0.58850465, 0.92214774, 0.58414579]],

       [[0.35505646, 0.82729614, 0.34533839],
        [0.60833387, 0.21239538, 0.3141275 ],
        [0.0638541 , 0.43951555, 0.43827512]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
a = np.array(range(25)).reshape(5,5)
a[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  6,  7,  8,  9],
       [10,  2, 12, 13, 14],
       [15, 16,  3, 18, 19],
       [20, 21, 22,  4, 24]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [33]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [37]:
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
x

array([[1.        , 0.222831  , 0.89490564, 0.44506436, 0.        ],
       [0.24956479, 0.85124897, 0.34597565, 0.84879138, 0.58711201],
       [0.38413114, 0.41106748, 0.45914969, 0.24485181, 0.27555996],
       [0.12391608, 0.63724184, 0.50085851, 0.78340569, 0.54318178],
       [0.27232952, 0.15754076, 0.23919501, 0.88402678, 0.36191122]])

# 5.  How to find common values between two arrays?

In [43]:
a1 = np.array(range(0,40,2))
a2 = list(range(0,20)) + [10,8,6,4,4,4,3,2,6,7,7,5,4,3]
print(np.intersect1d(a1, a2))

[ 0  2  4  6  8 10 12 14 16 18]


# 6.How to get the dates of yesterday, today and tomorrow?

In [46]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f'{yesterday}\n{today}\n{tomorrow}')

2020-07-26
2020-07-27
2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [63]:
y = [i for i in range(20) if (i % 2) == 0]
x = np.array(range(0,20,2))

np.allclose(x, y)


True

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [68]:
r = np.random.random(10)
print(r)
print('.............')
r[r.argmax()] = -1
print(r)

[0.57949912 0.27037147 0.29153512 0.7523558  0.27986078 0.84290576
 0.12705406 0.24302061 0.88416939 0.99256046]
.............
[ 0.57949912  0.27037147  0.29153512  0.7523558   0.27986078  0.84290576
  0.12705406  0.24302061  0.88416939 -1.        ]


# 9. How to print all the values of an array?

In [109]:
a = np.identity(4)
for i in a:
    for j in i:
        print(j,end = "-\n")

1.0-
0.0-
0.0-
0.0-
0.0-
1.0-
0.0-
0.0-
0.0-
0.0-
1.0-
0.0-
0.0-
0.0-
0.0-
1.0-


# 10.Subtract the mean of each row of a matrix

In [112]:
a = np.random.random((5,5))
s = a - a.mean(axis=1, keepdims=True)
s

array([[ 0.28869524, -0.17112081, -0.3035839 ,  0.43675557, -0.2507461 ],
       [-0.25665316, -0.28357313,  0.47535387,  0.48791783, -0.42304541],
       [ 0.52925516, -0.3078063 , -0.1091958 , -0.22772863,  0.11547556],
       [ 0.1604969 , -0.20738571,  0.05885265,  0.17737459, -0.18933843],
       [-0.33373594, -0.06347676,  0.1553619 , -0.08028481,  0.32213561]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [152]:
a = (range(0,20,2))

b = list(range(1,40,2))
print(f"original list :\n{b}")
for i in a:
    b[i] += 1
print(f"index: \n{list(a)}")
print(f"modified list :\n{b}")

original list :
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]
index: 
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
modified list :
[2, 3, 6, 7, 10, 11, 14, 15, 18, 19, 22, 23, 26, 27, 30, 31, 34, 35, 38, 39]


# 12.How to get the diagonal of a dot product?

In [162]:
a = np.arange(27).reshape(9, 3)
b = np.arange(9).reshape(3, 3)
np.einsum('ij,jk,ik->i', a, b, a)

array([   60,   672,  1932,  3840,  6396,  9600, 13452, 17952, 23100])

# 13.How to find the most frequent value in an array?

In [163]:
x = [1,2,3,4,5,6,7,5,4,3,2,1,1,1,12,3,4,5,6,4,3,2,2,1,1,1,2,3,4]
print(np.bincount(x).argmax())

1


# 14.How to get the n largest values of an array

In [166]:
a.argmax()

26

# 15.How to create a record array from a regular array?

In [178]:
x1=np.array([1,2,3,4])
x2=np.array(['a','b','c','d'])
x3=np.array([9,8,7,6])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')